# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.17.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
Z = np.zeros(10)
print(Z.size,Z.itemsize,Z.size*Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

10 8 80
80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
Z = np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
Z = np.arange(10,50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
Y = np.array([1,2,0,0,4,0])
print(Y)
Z = np.nonzero(Y)
print(Z)

[1 2 0 0 4 0]
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [3]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
Z = np.random.random((3,3,3))
print(Z)
Z = np.random.randint(1,20,size=(3,3,3))
print(Z)

[[[0.70568259 0.31700479 0.38554038]
  [0.89791813 0.01765911 0.81134404]
  [0.26749408 0.55755255 0.90748862]]

 [[0.6094968  0.59286715 0.12989375]
  [0.81926653 0.14353657 0.59801092]
  [0.36065583 0.43043633 0.26680336]]

 [[0.91667679 0.16673051 0.08361001]
  [0.78442853 0.83495126 0.65943316]
  [0.85174652 0.57765318 0.02124556]]]
[[[16  1 12]
  [17 15  6]
  [18  2  8]]

 [[17  4  5]
  [18 18 17]
  [18  7  2]]

 [[19 10  6]
  [ 4 14 15]
  [14 16 19]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
Z = np.random.randint(1,9,(10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

[[5.75557381e-01 6.33958180e-01 2.70219185e-02 8.81263930e-02
  1.60945161e-01 5.28091725e-01 8.53675718e-01 7.56526126e-01
  2.43266444e-01 8.31579720e-01]
 [2.67007668e-01 6.83044290e-01 5.32399569e-01 5.02242597e-01
  6.82649328e-01 4.07663025e-02 5.06637086e-02 2.93292392e-02
  6.66579336e-01 9.99429036e-01]
 [8.82928354e-01 3.16879485e-01 5.04139945e-01 8.14036561e-01
  6.13088412e-01 3.42699833e-01 4.13986042e-01 5.69302376e-01
  9.88438891e-02 5.49846609e-02]
 [4.74050863e-01 3.24750219e-01 5.04395042e-01 7.95889644e-01
  7.92878510e-02 3.68504778e-01 1.56946138e-01 2.54078745e-01
  9.13148391e-01 1.32954113e-01]
 [9.34149764e-01 4.03420085e-01 9.11068609e-01 2.82371092e-01
  3.17228781e-01 8.31676860e-01 3.92306584e-01 2.34418573e-01
  2.81586377e-01 5.53013373e-01]
 [8.19807201e-01 1.25188904e-02 2.64949449e-01 7.57203747e-01
  8.02689336e-01 6.46672105e-01 2.40177048e-01 4.73918672e-01
  5.63847489e-01 9.75964642e-01]
 [3.76060654e-01 9.21255608e-01 4.92298003e-02 6.66124226e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [20]:
Z = np.random.random((30))
# print(Z)
Zmean = Z.mean()
print(Zmean)

0.5429774416976934


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [34]:
Z = np.ones((10,10))
print('Before transformation: \n',Z)
Z[1:-1,1:-1]=0
print('After Transformation: \n',Z)

Z = np.zeros((10,10))
print('Before transformation: \n',Z)
# Z[[0,:],Z[-1,:],Z[:,0],Z[:,-1] = 1,1,1,1
Z[[0,-1],:],Z[:,[0,-1]] = 1,1
print('After Transformation: \n',Z)


Before transformation: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
After Transformation: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Before transformation: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [55]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width = 2, mode='constant', constant_values = 0)
print(Z)

# https://numpy.org/doc/stable/reference/generated/numpy.pad.html

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [54]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3, 3 * 0.1, 0.3 == 3 * 0.1)
print(np.nan)

nan
False
False
nan
True
0.3 0.30000000000000004 False
nan


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [58]:
np.info(np.diag)

 diag(*args, **kwargs)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> 

In [57]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [66]:
Z = np.ones((8,8))
print(Z)
Z[1::2,0::2]=0
Z[0::2,1::2]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [78]:
Z = np.zeros((6,7,8))
print(np.unravel_index(99,(6,7,8)))

# first 7*8
print(np.unravel_index(55,(6,7,8))) 

# second 7*8
print(np.unravel_index(111,(6,7,8)))

(1, 5, 3)
(0, 6, 7)
(1, 6, 7)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [85]:
Y = np.array([[0,1],[1,0]])
Z = np.tile(Y,(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [90]:
Z = np.random.random((5,5))
print(Z, Z.mean())
Z = (Z-np.mean(Z))/(np.std(Z))
print(Z, Z.mean())

[[0.45764725 0.62449868 0.06722283 0.82878421 0.14280538]
 [0.60979    0.42487132 0.75380278 0.41968652 0.70512829]
 [0.38439173 0.24235115 0.12585604 0.21691718 0.0165034 ]
 [0.34775578 0.27725422 0.79996573 0.15897111 0.68919742]
 [0.04699178 0.06453616 0.20508517 0.52245238 0.93231004]] 0.40259106205750933
[[ 0.20231245  0.8154338  -1.23236235  1.56611254 -0.95462261]
 [ 0.7613845   0.08187224  1.29058169  0.0628199   1.11171977]
 [-0.06687625 -0.5888263  -1.01690558 -0.68228735 -1.41873875]
 [-0.2015007  -0.46056957  1.46021458 -0.89521913  1.05317934]
 [-1.30670448 -1.24223495 -0.7257659   0.44044893  1.94653417]] -1.1546319456101628e-16


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [94]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [100]:
# dot for matrix multiplication m*n with n*p
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# another solution
Z = np.ones((2,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [107]:
Z = np.arange(15)
Z[(Z>=3) & (Z<=8)] *= -1
print(Z)

Z = np.arange(15)
Z[(Z<3) | (Z>8)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14]
[  0  -1  -2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [112]:
# np.info(np.sum)
print(sum(range(5),-1))
from numpy import sum
print(sum(range(5),0))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [133]:
Z = np.arange(1,5)

In [122]:
print(Z)
Z**Z

[1 2 3 4]


array([  1,   4,  27, 256])

In [123]:
print(Z)
2 << Z >> 2

[1 2 3 4]


array([1, 2, 4, 8])

In [132]:
Z = np.arange(-4,4)
print(Z)
Z <= -Z

[-4 -3 -2 -1  0  1  2  3]


array([ True,  True,  True,  True,  True, False, False, False])

In [135]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [136]:
Z/1/1

array([1., 2., 3., 4.])

In [137]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [145]:
# Wrong RuntimeWarning: invalid value encountered in true_divide
# np.array(0) / np.array(0) 

# Wrong RuntimeWarning: divide by zero encountered in floor_divide
# np.array(0) // np.array(0)

# correct
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [148]:
Z = np.random.uniform(-10,+10,10)
print(Z, Z.mean())
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-3.4415143   1.02503645 -2.71875882  7.31912341  6.09942003 -1.22354382
 -7.47867936 -9.03995601 -3.04709691 -2.09300035] -1.4598969682508178
[ -4.   2.  -3.   8.   7.  -2.  -8. -10.  -4.  -3.]
[ -4.   2.  -3.   8.   7.  -2.  -8. -10.  -4.  -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [153]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2)
print(np.intersect1d(Z1,Z2))

[1 1 7 1 2 6 1 6 2 3] [3 2 5 0 2 5 3 3 2 8]
[2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [156]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# # Back to sanity
_ = np.seterr(**defaults)

# # Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [157]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [161]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday, today, tomorrow)

2022-03-21 2022-03-22 2022-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [171]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [176]:
A = np.ones(3)*1
B = np.ones(3)*2
print(A,B)
np.add(A,B,out=B)
print(A,B)
np.divide(A,2,out=A)
print(A,B)
np.negative(A,out=A)
print(A,B)
np.multiply(A,B,out=A)
print(A,B)

[1. 1. 1.] [2. 2. 2.]
[1. 1. 1.] [3. 3. 3.]
[0.5 0.5 0.5] [3. 3. 3.]
[-0.5 -0.5 -0.5] [3. 3. 3.]
[-1.5 -1.5 -1.5] [3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [177]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[7.36232082 5.66750183 1.09559512 7.35364735 5.25210889 1.10112351
 0.4608649  6.64085848 8.5416481  4.78931194]
[7. 5. 1. 7. 5. 1. 0. 6. 8. 4.]
[7. 5. 1. 7. 5. 1. 0. 6. 8. 4.]
[7. 5. 1. 7. 5. 1. 0. 6. 8. 4.]
[7 5 1 7 5 1 0 6 8 4]
[7. 5. 1. 7. 5. 1. 0. 6. 8. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [186]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting use tile function
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [187]:
def generate():
    for x in range(10):
        yield x
        

Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [195]:
# np.info(np.linspace)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [204]:
Z = np.random.randint(1,10,10)
print(Z)
Z.sort()
print(Z)

[9 2 7 6 1 2 7 4 7 9]
[1 2 2 4 6 7 7 7 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [217]:
Z = np.arange(10000)

In [218]:
%%time
print(np.add.reduce(Z))

49995000
CPU times: user 456 µs, sys: 0 ns, total: 456 µs
Wall time: 318 µs


In [219]:
%%time
print(np.sum(Z))

49995000
CPU times: user 1.26 ms, sys: 0 ns, total: 1.26 ms
Wall time: 875 µs


#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)